#!/usr/bin/env ruby

git_tags = `git tag`.split

git_tags.each do |git_tag|
  tag = git_tag[1..-1]
  STDERR.puts "Building docker image #{tag} for git tag #{git_tag}..."
  system "git checkout #{git_tag}"
  system "docker build -t docker.io/gewo/ruby-code-quality-metrics:#{tag} ."
end

system 'docker build -t docker.io/gewo/ruby-code-quality-metrics:latest .'
